default_language_version:
  python: python3.12
default_install_hook_types: [commit-msg]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1 
    hooks:
      - id: mypy
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black