{{- $top := . -}}
{{- range $type := $top.Values.ClusterRole.type }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $type.name }}
  namespace: {{ $top.Release.Namespace }}
rules:
{{- toYaml $type.rules | nindent 0 }}

---
{{- end }}
